-- One immutable editorial edition per calendar date. Scheduled delivery reads
-- these rows and never invokes the collection or AI pipeline.
CREATE TABLE public.digest_publications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publication_date DATE NOT NULL UNIQUE,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  article_ids JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(article_ids) = 'object'),
  published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_digest_publications_date
  ON public.digest_publications(publication_date DESC);

ALTER TABLE public.digest_publications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_select"
  ON public.digest_publications
  FOR SELECT
  TO service_role
  USING (true);

CREATE POLICY "service_role_insert"
  ON public.digest_publications
  FOR INSERT
  TO service_role
  WITH CHECK (true);

REVOKE ALL ON TABLE public.digest_publications FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON TABLE public.digest_publications TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.digest_publications_id_seq TO service_role;

ALTER TABLE public.user_delivery_log
  ADD COLUMN publication_id BIGINT REFERENCES public.digest_publications(id) ON DELETE RESTRICT;

ALTER TABLE public.digest_runs
  ADD COLUMN prompt_version TEXT,
  ADD COLUMN analysis_schema_version INTEGER,
  ADD COLUMN quality_metrics JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.articles
  ADD COLUMN source_identity_verified BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX idx_user_delivery_publication
  ON public.user_delivery_log(publication_id)
  WHERE publication_id IS NOT NULL;

CREATE TABLE public.delivery_email_verifications (
  chat_id BIGINT PRIMARY KEY,
  email TEXT NOT NULL CHECK (length(email) BETWEEN 3 AND 320),
  code_hash TEXT NOT NULL CHECK (code_hash ~ '^[0-9a-f]{64}$'),
  expires_at TIMESTAMPTZ NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 5),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.delivery_email_verifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_access"
  ON public.delivery_email_verifications
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);
REVOKE ALL ON TABLE public.delivery_email_verifications FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.delivery_email_verifications TO service_role;

-- A function call is one transaction in Postgres. Any failed delete rolls the
-- entire privacy operation back instead of leaving a partially erased user.
CREATE OR REPLACE FUNCTION public.delete_user_data(p_chat_id BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF p_chat_id IS NULL OR p_chat_id <= 0 THEN
    RETURN FALSE;
  END IF;

  UPDATE public.user_preferences
  SET is_active = FALSE, updated_at = CURRENT_TIMESTAMP
  WHERE chat_id = p_chat_id;

  DELETE FROM public.user_delivery_log WHERE chat_id = p_chat_id;
  DELETE FROM public.alert_delivery_log WHERE chat_id = p_chat_id;
  DELETE FROM public.product_events WHERE chat_id = p_chat_id;
  DELETE FROM public.price_watches WHERE chat_id = p_chat_id;
  DELETE FROM public.command_usage WHERE chat_id = p_chat_id;
  DELETE FROM public.article_validations WHERE chat_id = p_chat_id;
  DELETE FROM public.delivery_email_verifications WHERE chat_id = p_chat_id;
  DELETE FROM public.user_preferences WHERE chat_id = p_chat_id;

  RETURN TRUE;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.delete_user_data(BIGINT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.delete_user_data(BIGINT)
  TO service_role;

CREATE OR REPLACE FUNCTION public.verify_delivery_email(
  p_chat_id BIGINT,
  p_code_hash TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  pending public.delivery_email_verifications%ROWTYPE;
BEGIN
  IF p_chat_id IS NULL OR p_chat_id <= 0 OR p_code_hash IS NULL
     OR p_code_hash !~ '^[0-9a-f]{64}$' THEN
    RETURN FALSE;
  END IF;

  SELECT * INTO pending
  FROM public.delivery_email_verifications
  WHERE chat_id = p_chat_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN FALSE;
  END IF;

  IF pending.expires_at <= CURRENT_TIMESTAMP OR pending.attempts >= 5 THEN
    DELETE FROM public.delivery_email_verifications WHERE chat_id = p_chat_id;
    RETURN FALSE;
  END IF;

  UPDATE public.delivery_email_verifications
  SET attempts = attempts + 1, updated_at = CURRENT_TIMESTAMP
  WHERE chat_id = p_chat_id;

  IF pending.code_hash <> p_code_hash THEN
    RETURN FALSE;
  END IF;

  INSERT INTO public.user_preferences (chat_id, delivery_email)
  VALUES (p_chat_id, pending.email)
  ON CONFLICT (chat_id) DO UPDATE
  SET delivery_email = EXCLUDED.delivery_email,
      updated_at = CURRENT_TIMESTAMP;

  DELETE FROM public.delivery_email_verifications WHERE chat_id = p_chat_id;
  RETURN TRUE;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.verify_delivery_email(BIGINT, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.verify_delivery_email(BIGINT, TEXT)
  TO service_role;

-- Make Data API exposure intentional. RLS and SQL privileges are separate;
-- both must allow a request. Private user/delivery/publication tables receive
-- no client grant after this reset.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;

GRANT SELECT (
  id, run_date, status, articles_collected, articles_processed, batches_run,
  total_tokens_used, duration_seconds, created_at, capabilities, degraded_stages
) ON public.digest_runs TO anon, authenticated;

GRANT SELECT (
  id, title, url, source, impact, impact_score, effective_score,
  ranking_explanation, is_sec_filing, category, affected_stocks, summary,
  reason, bear_case, thumbs_up, thumbs_down, created_at
) ON public.articles TO anon, authenticated;

GRANT SELECT (
  id, digest_run_id, feed_name, status, articles_fetched, response_time_ms, created_at
) ON public.pipeline_health TO anon, authenticated;

GRANT SELECT ON TABLE
  public.sector_activity,
  public.stock_mentions,
  public.capex_tracking,
  public.daily_metrics,
  public.stock_prices,
  public.sec_filings,
  public.daily_derived_metrics,
  public.delivery_metrics_daily,
  public.ticker_theses,
  public.ticker_thesis_history,
  public.ranking_quality_daily
TO anon, authenticated;

REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.search_articles(TEXT, INTEGER, INTEGER)
  TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.claim_user_delivery(BIGINT, DATE, INTEGER)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_high_impact_alert(BIGINT, TEXT, INTEGER)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.refresh_delivery_metrics_daily()
  TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_old_data()
  TO service_role;
GRANT EXECUTE ON FUNCTION public.delete_user_data(BIGINT)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.verify_delivery_email(BIGINT, TEXT)
  TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, anon, authenticated;
