-- v1.0.1: keep individual feedback private while exposing only daily quality
-- aggregates to the read-only dashboard.

-- The old daily_metrics.feedback_ratings column contained a JSON document with
-- both ratings and raw Telegram comments. Keep an exact private copy before the
-- public column is removed. Scalar rows below also let us backfill the public
-- aggregate without making the legacy payload public again.
CREATE TABLE public.digest_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id BIGINT CHECK (chat_id IS NULL OR chat_id > 0),
  feedback_date DATE NOT NULL,
  rating SMALLINT CHECK (rating BETWEEN 1 AND 5),
  comment TEXT CHECK (comment IS NULL OR length(comment) <= 2000),
  source TEXT NOT NULL DEFAULT 'telegram'
    CHECK (source IN ('telegram', 'legacy_daily_metrics')),
  legacy_payload TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT digest_feedback_content_check CHECK (
    rating IS NOT NULL OR comment IS NOT NULL OR legacy_payload IS NOT NULL
  )
);

CREATE INDEX idx_digest_feedback_chat_date
  ON public.digest_feedback(chat_id, feedback_date DESC)
  WHERE chat_id IS NOT NULL;
CREATE INDEX idx_digest_feedback_date
  ON public.digest_feedback(feedback_date DESC);

ALTER TABLE public.digest_feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_access" ON public.digest_feedback
  FOR ALL TO service_role USING (true) WITH CHECK (true);
REVOKE ALL ON TABLE public.digest_feedback FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.digest_feedback TO service_role;
REVOKE ALL ON SEQUENCE public.digest_feedback_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.digest_feedback_id_seq TO service_role;

-- Archive every legacy payload exactly as it was stored. This row has no chat
-- identity because the old JSON format did not retain one.
INSERT INTO public.digest_feedback (
  feedback_date, source, legacy_payload, created_at
)
SELECT date, 'legacy_daily_metrics', feedback_ratings, COALESCE(created_at, CURRENT_TIMESTAMP)
FROM public.daily_metrics
WHERE feedback_ratings IS NOT NULL;

-- Preserve the useful scalar values for historical aggregate reporting. The
-- legacy writer emitted valid JSON with ratings/comments arrays; malformed rows
-- remain safely preserved in legacy_payload and are not allowed to abort the
-- migration.
DO $$
DECLARE
  row_data RECORD;
BEGIN
  FOR row_data IN
    SELECT date, feedback_ratings, created_at
    FROM public.daily_metrics
    WHERE feedback_ratings IS NOT NULL
      AND feedback_ratings ~ '^\s*\{'
  LOOP
    BEGIN
      INSERT INTO public.digest_feedback (
        feedback_date, rating, source, created_at
      )
      SELECT row_data.date, value::SMALLINT, 'legacy_daily_metrics',
             COALESCE(row_data.created_at, CURRENT_TIMESTAMP)
      FROM jsonb_array_elements_text(
        (row_data.feedback_ratings::jsonb -> 'ratings')
      ) AS rating_values(value)
      WHERE value ~ '^[1-5]$';
    EXCEPTION WHEN others THEN
      -- Preserve valid ratings even when the legacy comments field is bad.
      NULL;
    END;

    BEGIN
      INSERT INTO public.digest_feedback (
        feedback_date, comment, source, created_at
      )
      SELECT row_data.date, value, 'legacy_daily_metrics',
             COALESCE(row_data.created_at, CURRENT_TIMESTAMP)
      FROM jsonb_array_elements_text(
        (row_data.feedback_ratings::jsonb -> 'comments')
      ) AS comment_values(value)
      WHERE value <> '' AND length(value) <= 2000;
    EXCEPTION WHEN others THEN
      -- Oversized/malformed comments are omitted; the exact original payload
      -- is already archived above and remains available to the service role.
      NULL;
    END;
  END LOOP;
END;
$$;

-- Public aggregate contains no chat IDs, comments, or raw feedback rows.
CREATE TABLE public.digest_feedback_daily (
  feedback_date DATE PRIMARY KEY,
  total_votes INTEGER NOT NULL DEFAULT 0 CHECK (total_votes >= 0),
  rating_sum INTEGER NOT NULL DEFAULT 0 CHECK (rating_sum >= 0),
  rating_1_count INTEGER NOT NULL DEFAULT 0 CHECK (rating_1_count >= 0),
  rating_2_count INTEGER NOT NULL DEFAULT 0 CHECK (rating_2_count >= 0),
  rating_3_count INTEGER NOT NULL DEFAULT 0 CHECK (rating_3_count >= 0),
  rating_4_count INTEGER NOT NULL DEFAULT 0 CHECK (rating_4_count >= 0),
  rating_5_count INTEGER NOT NULL DEFAULT 0 CHECK (rating_5_count >= 0),
  comment_count INTEGER NOT NULL DEFAULT 0 CHECK (comment_count >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_digest_feedback_daily_date
  ON public.digest_feedback_daily(feedback_date DESC);

INSERT INTO public.digest_feedback_daily (
  feedback_date,
  total_votes,
  rating_sum,
  rating_1_count,
  rating_2_count,
  rating_3_count,
  rating_4_count,
  rating_5_count,
  comment_count
)
SELECT
  feedback_date,
  COUNT(*) FILTER (WHERE rating IS NOT NULL)::INTEGER,
  COALESCE(SUM(rating), 0)::INTEGER,
  COUNT(*) FILTER (WHERE rating = 1)::INTEGER,
  COUNT(*) FILTER (WHERE rating = 2)::INTEGER,
  COUNT(*) FILTER (WHERE rating = 3)::INTEGER,
  COUNT(*) FILTER (WHERE rating = 4)::INTEGER,
  COUNT(*) FILTER (WHERE rating = 5)::INTEGER,
  COUNT(*) FILTER (WHERE comment IS NOT NULL)::INTEGER
FROM public.digest_feedback
GROUP BY feedback_date;

ALTER TABLE public.digest_feedback_daily ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_read" ON public.digest_feedback_daily
  FOR SELECT TO anon, authenticated USING (total_votes >= 5);
CREATE POLICY "service_role_write" ON public.digest_feedback_daily
  FOR ALL TO service_role USING (true) WITH CHECK (true);
REVOKE ALL ON TABLE public.digest_feedback_daily FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.digest_feedback_daily TO anon, authenticated;
GRANT ALL ON TABLE public.digest_feedback_daily TO service_role;

-- Remove the legacy raw-comment surface only after the private archive and
-- sanitized aggregate have been built.
ALTER TABLE public.daily_metrics DROP COLUMN IF EXISTS feedback_ratings;

-- A single service-role RPC inserts the private row and increments the public
-- daily counters in one transaction. No client role can call it directly.
CREATE OR REPLACE FUNCTION public.submit_digest_feedback(
  p_chat_id BIGINT,
  p_feedback_date DATE,
  p_rating SMALLINT,
  p_comment TEXT DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  normalized_comment TEXT;
BEGIN
  normalized_comment = NULLIF(BTRIM(p_comment), '');

  IF p_chat_id IS NULL OR p_chat_id <= 0
     OR p_feedback_date IS NULL
     OR p_rating IS NULL OR p_rating < 1 OR p_rating > 5
     OR (normalized_comment IS NOT NULL AND length(normalized_comment) > 2000) THEN
    RETURN FALSE;
  END IF;

  INSERT INTO public.digest_feedback (
    chat_id, feedback_date, rating, comment, source
  ) VALUES (
    p_chat_id, p_feedback_date, p_rating, normalized_comment, 'telegram'
  );

  INSERT INTO public.digest_feedback_daily (
    feedback_date,
    total_votes,
    rating_sum,
    rating_1_count,
    rating_2_count,
    rating_3_count,
    rating_4_count,
    rating_5_count,
    comment_count,
    updated_at
  ) VALUES (
    p_feedback_date,
    1,
    p_rating,
    CASE WHEN p_rating = 1 THEN 1 ELSE 0 END,
    CASE WHEN p_rating = 2 THEN 1 ELSE 0 END,
    CASE WHEN p_rating = 3 THEN 1 ELSE 0 END,
    CASE WHEN p_rating = 4 THEN 1 ELSE 0 END,
    CASE WHEN p_rating = 5 THEN 1 ELSE 0 END,
    CASE WHEN normalized_comment IS NULL THEN 0 ELSE 1 END,
    CURRENT_TIMESTAMP
  )
  ON CONFLICT (feedback_date) DO UPDATE SET
    total_votes = public.digest_feedback_daily.total_votes + 1,
    rating_sum = public.digest_feedback_daily.rating_sum + EXCLUDED.rating_sum,
    rating_1_count = public.digest_feedback_daily.rating_1_count + EXCLUDED.rating_1_count,
    rating_2_count = public.digest_feedback_daily.rating_2_count + EXCLUDED.rating_2_count,
    rating_3_count = public.digest_feedback_daily.rating_3_count + EXCLUDED.rating_3_count,
    rating_4_count = public.digest_feedback_daily.rating_4_count + EXCLUDED.rating_4_count,
    rating_5_count = public.digest_feedback_daily.rating_5_count + EXCLUDED.rating_5_count,
    comment_count = public.digest_feedback_daily.comment_count + EXCLUDED.comment_count,
    updated_at = CURRENT_TIMESTAMP;

  RETURN TRUE;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.submit_digest_feedback(BIGINT, DATE, SMALLINT, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_digest_feedback(BIGINT, DATE, SMALLINT, TEXT)
  TO service_role;

-- Extend the existing transactional delete boundary to erase individual
-- feedback rows owned by the requested Telegram chat.
CREATE OR REPLACE FUNCTION public.delete_user_data(p_chat_id BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF p_chat_id IS NULL OR p_chat_id <= 0 THEN
    RETURN FALSE;
  END IF;

  UPDATE public.user_preferences
  SET is_active = FALSE, updated_at = CURRENT_TIMESTAMP
  WHERE chat_id = p_chat_id;

  DELETE FROM public.user_delivery_log WHERE chat_id = p_chat_id;
  DELETE FROM public.alert_delivery_log WHERE chat_id = p_chat_id;
  DELETE FROM public.product_events WHERE chat_id = p_chat_id;
  DELETE FROM public.price_watches WHERE chat_id = p_chat_id;
  DELETE FROM public.command_usage WHERE chat_id = p_chat_id;
  DELETE FROM public.article_validations WHERE chat_id = p_chat_id;
  DELETE FROM public.digest_feedback WHERE chat_id = p_chat_id;
  DELETE FROM public.delivery_email_verifications WHERE chat_id = p_chat_id;
  DELETE FROM public.user_preferences WHERE chat_id = p_chat_id;

  RETURN TRUE;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.delete_user_data(BIGINT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.delete_user_data(BIGINT)
  TO service_role;

-- Retain feedback for 180 days, matching private product-event retention.
CREATE OR REPLACE FUNCTION public.cleanup_old_data()
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  deleted_articles INT;
  deleted_pipeline INT;
  deleted_ai_usage INT;
  deleted_delivery_log INT;
  deleted_alert_log INT;
  deleted_product_events INT;
  deleted_feedback INT;
  deleted_capex INT;
BEGIN
  DELETE FROM public.articles
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '90 days';
  GET DIAGNOSTICS deleted_articles = ROW_COUNT;

  DELETE FROM public.pipeline_health
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '30 days';
  GET DIAGNOSTICS deleted_pipeline = ROW_COUNT;

  DELETE FROM public.ai_usage
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '90 days';
  GET DIAGNOSTICS deleted_ai_usage = ROW_COUNT;

  DELETE FROM public.user_delivery_log
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '90 days';
  GET DIAGNOSTICS deleted_delivery_log = ROW_COUNT;

  DELETE FROM public.alert_delivery_log
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '90 days';
  GET DIAGNOSTICS deleted_alert_log = ROW_COUNT;

  DELETE FROM public.product_events
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '180 days';
  GET DIAGNOSTICS deleted_product_events = ROW_COUNT;

  DELETE FROM public.digest_feedback
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '180 days';
  GET DIAGNOSTICS deleted_feedback = ROW_COUNT;

  DELETE FROM public.digest_feedback_daily
  WHERE feedback_date < CURRENT_DATE - INTERVAL '180 days';

  DELETE FROM public.capex_tracking
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '365 days';
  GET DIAGNOSTICS deleted_capex = ROW_COUNT;

  RAISE NOTICE 'Retention cleanup: articles=%, pipeline_health=%, ai_usage=%, delivery_log=%, alert_log=%, product_events=%, digest_feedback=%, capex=%',
    deleted_articles,
    deleted_pipeline,
    deleted_ai_usage,
    deleted_delivery_log,
    deleted_alert_log,
    deleted_product_events,
    deleted_feedback,
    deleted_capex;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.cleanup_old_data() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_old_data() TO service_role;
