CREATE SCHEMA IF NOT EXISTS extensions;
ALTER EXTENSION vector SET SCHEMA extensions;

-- Persist alert claims so repeated or overlapping digest runs cannot send the
-- same high-impact article to the same user more than once.
CREATE TABLE public.alert_delivery_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id BIGINT NOT NULL,
  content_hash TEXT NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
  status TEXT NOT NULL CHECK (status IN ('pending', 'success', 'failed')),
  details TEXT,
  claimed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (chat_id, content_hash)
);

CREATE INDEX idx_alert_delivery_claim_state
  ON public.alert_delivery_log(status, claimed_at)
  WHERE status = 'pending';

CREATE INDEX idx_alert_delivery_created_at
  ON public.alert_delivery_log(created_at);

ALTER TABLE public.alert_delivery_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_access"
  ON public.alert_delivery_log
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

REVOKE ALL ON TABLE public.alert_delivery_log FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.alert_delivery_log TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.alert_delivery_log_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.claim_high_impact_alert(
  p_chat_id BIGINT,
  p_content_hash TEXT,
  p_stale_after_seconds INTEGER DEFAULT 1800
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  did_claim BOOLEAN;
BEGIN
  IF p_chat_id IS NULL OR p_content_hash !~ '^[0-9a-f]{64}$' THEN
    RETURN FALSE;
  END IF;

  INSERT INTO public.alert_delivery_log (
    chat_id,
    content_hash,
    status,
    details,
    claimed_at
  )
  VALUES (
    p_chat_id,
    p_content_hash,
    'pending',
    'claimed - send in progress',
    CURRENT_TIMESTAMP
  )
  ON CONFLICT (chat_id, content_hash) DO UPDATE
  SET
    status = 'pending',
    details = 'claimed - send in progress',
    claimed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
  WHERE public.alert_delivery_log.status = 'failed'
     OR (
       public.alert_delivery_log.status = 'pending'
       AND (
         public.alert_delivery_log.claimed_at IS NULL
         OR public.alert_delivery_log.claimed_at < CURRENT_TIMESTAMP -
           GREATEST(p_stale_after_seconds, 1) * INTERVAL '1 second'
       )
     )
  RETURNING TRUE INTO did_claim;

  RETURN COALESCE(did_claim, FALSE);
END;
$$;

REVOKE EXECUTE ON FUNCTION public.claim_high_impact_alert(BIGINT, TEXT, INTEGER)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_high_impact_alert(BIGINT, TEXT, INTEGER)
  TO service_role;

-- Private product events support onboarding, activation, retention, and
-- delivery-lateness analysis without exposing Telegram identities publicly.
CREATE TABLE public.product_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL CHECK (
    event_name IN (
      'onboarding_started',
      'onboarding_completed',
      'delivery_succeeded',
      'delivery_failed'
    )
  ),
  chat_id BIGINT NOT NULL,
  properties JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_product_events_name_created
  ON public.product_events(event_name, created_at DESC);

CREATE INDEX idx_product_events_chat_created
  ON public.product_events(chat_id, created_at DESC);

ALTER TABLE public.product_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_access"
  ON public.product_events
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

REVOKE ALL ON TABLE public.product_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.product_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.product_events_id_seq TO service_role;

-- Search through the Data API with the same expression used by idx_articles_fts.
-- SECURITY INVOKER preserves the articles table's public-read RLS boundary.
GRANT SELECT ON TABLE public.articles TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.search_articles(
  p_query TEXT,
  p_limit INTEGER DEFAULT 20,
  p_offset INTEGER DEFAULT 0
)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
  WITH search_query AS (
    SELECT websearch_to_tsquery('english', LEFT(COALESCE(p_query, ''), 80)) AS value
  ),
  matched AS (
    SELECT
      a.*,
      ts_rank(
        to_tsvector(
          'english',
          COALESCE(a.title, '') || ' ' ||
          COALESCE(a.summary, '') || ' ' ||
          COALESCE(a.source, '') || ' ' ||
          COALESCE(a.category, '')
        ),
        q.value
      ) AS search_rank
    FROM public.articles AS a
    CROSS JOIN search_query AS q
    WHERE numnode(q.value) > 0
      AND to_tsvector(
        'english',
        COALESCE(a.title, '') || ' ' ||
        COALESCE(a.summary, '') || ' ' ||
        COALESCE(a.source, '') || ' ' ||
        COALESCE(a.category, '')
      ) @@ q.value
  ),
  page AS (
    SELECT
      id,
      title,
      url,
      source,
      impact,
      impact_score,
      effective_score,
      ranking_explanation,
      is_sec_filing,
      category,
      affected_stocks,
      summary,
      reason,
      bear_case,
      thumbs_up,
      thumbs_down,
      created_at
    FROM matched
    ORDER BY search_rank DESC, impact_score DESC NULLS LAST, created_at DESC, id DESC
    LIMIT LEAST(GREATEST(COALESCE(p_limit, 20), 1), 100)
    OFFSET GREATEST(COALESCE(p_offset, 0), 0)
  )
  SELECT jsonb_build_object(
    'articles', COALESCE((SELECT jsonb_agg(to_jsonb(page)) FROM page), '[]'::jsonb),
    'total', (SELECT COUNT(*) FROM matched)
  );
$$;

REVOKE EXECUTE ON FUNCTION public.search_articles(TEXT, INTEGER, INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.search_articles(TEXT, INTEGER, INTEGER)
  TO anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public.cleanup_old_data()
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  deleted_articles INT;
  deleted_pipeline INT;
  deleted_ai_usage INT;
  deleted_delivery_log INT;
  deleted_alert_log INT;
  deleted_product_events INT;
  deleted_capex INT;
BEGIN
  DELETE FROM public.articles
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '90 days';
  GET DIAGNOSTICS deleted_articles = ROW_COUNT;

  DELETE FROM public.pipeline_health
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '30 days';
  GET DIAGNOSTICS deleted_pipeline = ROW_COUNT;

  DELETE FROM public.ai_usage
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '90 days';
  GET DIAGNOSTICS deleted_ai_usage = ROW_COUNT;

  DELETE FROM public.user_delivery_log
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '90 days';
  GET DIAGNOSTICS deleted_delivery_log = ROW_COUNT;

  DELETE FROM public.alert_delivery_log
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '90 days';
  GET DIAGNOSTICS deleted_alert_log = ROW_COUNT;

  DELETE FROM public.product_events
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '180 days';
  GET DIAGNOSTICS deleted_product_events = ROW_COUNT;

  DELETE FROM public.capex_tracking
  WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '365 days';
  GET DIAGNOSTICS deleted_capex = ROW_COUNT;

  RAISE NOTICE 'Retention cleanup: articles=%, pipeline_health=%, ai_usage=%, delivery_log=%, alert_log=%, product_events=%, capex=%',
    deleted_articles,
    deleted_pipeline,
    deleted_ai_usage,
    deleted_delivery_log,
    deleted_alert_log,
    deleted_product_events,
    deleted_capex;
END;
$$;
